name: bluethooth_lab5
description: "Aplicación Flutter para enviar archivos por Bluetooth usando el sistema nativo de Android"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.0.0
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
